### ISSUE TITLE
Migrate from a qooxdoo v5 "contrib" to v6 "package"

### ISSUE THREAD

**Issue by cboulanger** [adrelino/qooxdoo-extensions#1]
The qooxdoo dev team invites you to upgrade your contrib project to qooxdoo v6 (very soon to be release in beta). Please have a look at the documentation at

https://www.qooxdoo.org/docs/#/cli/packages

The previous "contrib" architecture has been deprecated; qooxdoo v6 will be using "packages" with different `Manifest.json` entries compared to the old system (see [here](https://www.qooxdoo.org/docs/#/configuration/Manifest)). The packages are managed using CLI commands that support the use, creation and mainenance of packages.

Upgrading your project to version 6 should pose no major problems. Version 6 adds a whole slew of new and exciting features, but stays almost 100% backwards compatible with version 5. The major difference is the [new tool chain and compiler based on NodeJS](http://www.qooxdoo.org/docs/#/cli/commands). See [here on how to get started](http://www.qooxdoo.org/docs/#/?id=getting-started). If you run into problems, feel free to ask questions on [Gitter](https://gitter.im/qooxdoo/qooxdoo) or [StackOverflow](https://stackoverflow.com/questions/tagged/qooxdoo).

Once you have re-published your project as a package, it will (with a delay of a day or so) show up in the [Qooxdoo Package Browser](http://www.qooxdoo.org/qxl.packagebrowser/#). If you add a standalone demo application by providing the necessary instructions [in the `compile.json` configuration file](http://www.qooxdoo.org/docs/#/configuration/compile?id=applications), a live version will be showcased there.

We'd be thrilled to see your new qooxdoo package in the package browser soon, and please use the [Gitter](https://gitter.im/qooxdoo/qooxdoo) chat to announce it!

**Comment by adrelino** [comment]
I'm working on it now starting with b4cba195bbff922b23a8d2c34f943af219e8cff8
